export type Product = {
  id: number;
  name: string;
  price: number;
  currency: string;
  category: string;
  vendorId: number;
  vendorName: string;
  rating: number;
  reviewsCount: number;
  model: string;
  images: string[];
  description: string;
  shortDescription: string;
  features: string[];
  specs: Record<string, string>;
  tags: string[];
  available3D: boolean;
  createdAt: string;
};

export type Category = {
  id: number;
  name: string;
  description: string;
  image: string;
  color: string;
};

export type Vendor = {
  id: number;
  name: string;
  tagline: string;
  rating: number;
  products: number;
  avatar: string;
  location: string;
};

export type Review = {
  id: number;
  productId: number;
  author: string;
  rating: number;
  title: string;
  body: string;
  date: string;
};

export type Order = {
  id: string;
  reference: string;
  status: 'Pending' | 'Confirmed' | 'Shipped' | 'Delivered' | 'Cancelled';
  total: number;
  date: string;
  items: { productId: number; quantity: number; name: string; price: number }[];
};

export type NotificationItem = {
  id: number;
  title: string;
  description: string;
  date: string;
  type: 'info' | 'success' | 'warning' | 'alert';
  unread: boolean;
};

export type PurchaseRequest = {
  id: number;
  productId: number;
  productName: string;
  vendorId: number;
  vendorName: string;
  status: 'Pending' | 'Accepted' | 'Declined';
  requestedAt: string;
  quantity: number;
};

export type InventoryItem = {
  productId: number;
  productName: string;
  stock: number;
  status: 'In stock' | 'Low stock' | 'Out of stock';
};

export type AnalyticsSnapshot = {
  dates: string[];
  sales: number[];
  views: number[];
  popularity: number[];
  conversions: number[];
};

export type AIStatus = {
  id: number;
  productName: string;
  stage: string;
  progress: number;
  eta: string;
  status: 'processing' | 'success' | 'failed';
};

export type UserProfile = {
  id: number;
  name: string;
  email: string;
  role: 'customer' | 'vendor';
  membership: string;
  location: string;
  preferences: string[];
  avatar: string;
  bio: string;
};

export const categories: Category[] = [
  {
    id: 1,
    name: 'Furniture',
    description: 'Curated home pieces with premium craftsmanship.',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
    color: 'from-slate-500 to-slate-700',
  },
  {
    id: 2,
    name: 'Fashion',
    description: 'Bold statement wear inspired by modern African design.',
    image: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?auto=format&fit=crop&w=1200&q=80',
    color: 'from-pink-500 to-pink-700',
  },
  {
    id: 3,
    name: 'Lifestyle',
    description: 'Everyday essentials refined for premium living.',
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80',
    color: 'from-amber-500 to-orange-700',
  },
  {
    id: 4,
    name: '3D Tech',
    description: 'Immersive products generated by AI-powered 3D transformation.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    color: 'from-cyan-500 to-blue-700',
  },
];

export const vendors: Vendor[] = [
  {
    id: 1,
    name: 'LuxeStudio',
    tagline: 'Minimalist furniture with rich textures.',
    rating: 4.9,
    products: 28,
    avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=80',
    location: 'Buea, Cameroon',
  },
  {
    id: 2,
    name: 'Kora Collective',
    tagline: 'Modern African fashion for every wardrobe.',
    rating: 4.8,
    products: 18,
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    location: 'Douala, Cameroon',
  },
  {
    id: 3,
    name: 'Verve Works',
    tagline: 'Curated lifestyle products with a future feel.',
    rating: 4.7,
    products: 12,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    location: 'Yaoundé, Cameroon',
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: 'Royal Chair',
    price: 75000,
    currency: 'FCFA',
    category: 'Furniture',
    vendorId: 1,
    vendorName: 'LuxeStudio',
    rating: 4.9,
    reviewsCount: 86,
    model: 'chair.glb',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A statement lounge chair with curved armrests, crafted from warm natural materials and designed for premium living rooms.',
    shortDescription: 'Handcrafted comfort for modern interiors.',
    features: ['3D preview available', 'Soft premium upholstery', 'Eco-conscious materials', 'Curved silhouette design'],
    specs: {
      Material: 'Mahogany wood & linen blend',
      Dimensions: '82cm x 76cm x 108cm',
      Weight: '12 kg',
      Color: 'Stone & Wheat',
    },
    tags: ['chair', 'lounge', 'wood', 'comfortable', 'premium'],
    available3D: true,
    createdAt: '2025-09-14',
  },
  {
    id: 2,
    name: 'Heritage Wrap Dress',
    price: 42000,
    currency: 'FCFA',
    category: 'Fashion',
    vendorId: 2,
    vendorName: 'Kora Collective',
    rating: 4.8,
    reviewsCount: 54,
    model: 'shirt.glb',
    images: [
      'https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A sculpted wrap dress that blends contemporary tailoring with rich African patterns for elevated day-to-night styling.',
    shortDescription: 'Tailored elegance with cultural details.',
    features: ['3D fit preview', 'Premium cotton blend', 'Cinch waist silhouette', 'Limited capsule edition'],
    specs: {
      Material: 'Cotton blend',
      Sizes: 'S, M, L, XL',
      Care: 'Hand wash cold',
      Color: 'Ebony & Gold',
    },
    tags: ['dress', 'wrap', 'fashion', 'textile', 'premium'],
    available3D: true,
    createdAt: '2025-11-02',
  },
  {
    id: 3,
    name: 'Coffee Table',
    price: 8000,
    currency: 'FCFA',
    category: 'Furniture',
    vendorId: 1,
    vendorName: 'LuxeStudio',
    rating: 4.7,
    reviewsCount: 72,
    model: 'coffee.glb',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A sculptural coffee table with layered textures and a minimalist frame, designed to anchor lounge spaces with subtle craftsmanship.',
    shortDescription: 'Modern minimalism for calm interiors.',
    features: ['3D model integration', 'Solid ash top', 'Wide stance base', 'Easy-care surface'],
    specs: {
      Material: 'Ash wood & matte lacquer',
      Dimensions: '120cm x 60cm x 38cm',
      Weight: '18 kg',
      Color: 'Warm Clay',
    },
    tags: ['table', 'coffee', 'modern', 'living room'],
    available3D: true,
    createdAt: '2025-08-10',
  },
  {
    id: 4,
    name: 'Velocity Sport',
    price: 15000,
    currency: 'FCFA',
    category: '3D Tech',
    vendorId: 3,
    vendorName: 'Verve Works',
    rating: 4.6,
    reviewsCount: 49,
    model: 'bag.glb',
    images: [
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A concept-inspired product for trendsetters exploring premium lifestyle design and high-energy branded experiences.',
    shortDescription: 'Dynamic design for modern creators.',
    features: ['AI 3D preview', 'Bold performance styling', 'Fast-rising popularity', 'Limited-run release'],
    specs: {
      Material: 'Composite tech shell',
      Dimensions: '40cm x 18cm x 12cm',
      Weight: '7.5 kg',
      Color: 'Midnight Cyan',
    },
    tags: ['tech', 'concept', 'lifestyle', '3d'],
    available3D: true,
    createdAt: '2025-10-21',
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    productId: 1,
    author: 'Amina T.',
    rating: 5,
    title: 'A beautifully designed lounge seat',
    body: 'The chair feels luxurious, and the mock 3D preview made it easy to imagine in my living room. Delivery was smooth too.',
    date: '2026-01-12',
  },
  {
    id: 2,
    productId: 2,
    author: 'Samuel K.',
    rating: 4,
    title: 'Perfect fit and vibrant details',
    body: 'The wrap dress is even better in person. I loved the quality and the way the AI preview showed every angle of the fabric.',
    date: '2026-02-03',
  },
  {
    id: 3,
    productId: 3,
    author: 'Mae J.',
    rating: 5,
    title: 'Modern and understated',
    body: 'The coffee table elevated my whole lounge area. The product page felt premium and helped me decide quickly.',
    date: '2026-03-07',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-3029',
    reference: 'RQ-9942',
    status: 'Delivered',
    total: 85000,
    date: '2026-03-25',
    items: [
      { productId: 1, quantity: 1, name: 'Royal Chair', price: 75000 },
      { productId: 3, quantity: 1, name: 'Coffee Table', price: 8000 },
    ],
  },
  {
    id: 'ORD-3011',
    reference: 'RQ-9925',
    status: 'Confirmed',
    total: 42000,
    date: '2026-04-08',
    items: [{ productId: 2, quantity: 1, name: 'Heritage Wrap Dress', price: 42000 }],
  },
];

export const notifications: NotificationItem[] = [
  {
    id: 1,
    title: 'New AI recommendations ready',
    description: 'Your personalized home feed has been updated with 12 new matches.',
    date: 'Today',
    type: 'info',
    unread: true,
  },
  {
    id: 2,
    title: 'Vendor request received',
    description: 'Verve Works received a new purchase request for the Velocity Sport product.',
    date: 'Yesterday',
    type: 'success',
    unread: false,
  },
  {
    id: 3,
    title: 'AI 3D generation completed',
    description: 'Your latest uploaded product preview is ready for vendor review.',
    date: '2 days ago',
    type: 'success',
    unread: false,
  },
];

export const purchaseRequests: PurchaseRequest[] = [
  {
    id: 1,
    productId: 1,
    productName: 'Royal Chair',
    vendorId: 1,
    vendorName: 'LuxeStudio',
    status: 'Pending',
    requestedAt: '2026-04-17',
    quantity: 1,
  },
  {
    id: 2,
    productId: 2,
    productName: 'Heritage Wrap Dress',
    vendorId: 2,
    vendorName: 'Kora Collective',
    status: 'Accepted',
    requestedAt: '2026-04-14',
    quantity: 2,
  },
];

export const inventory: InventoryItem[] = [
  { productId: 1, productName: 'Royal Chair', stock: 12, status: 'In stock' },
  { productId: 2, productName: 'Heritage Wrap Dress', stock: 4, status: 'Low stock' },
  { productId: 3, productName: 'Coffee Table', stock: 8, status: 'In stock' },
  { productId: 4, productName: 'Velocity Sport', stock: 1, status: 'Low stock' },
];

export const analyticsSnapshot: AnalyticsSnapshot = {
  dates: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  sales: [12, 18, 20, 22, 27, 30],
  views: [320, 420, 520, 640, 790, 910],
  popularity: [75, 84, 92, 88, 96, 99],
  conversions: [7, 10, 12, 14, 18, 20],
};

export const aiStatus: AIStatus[] = [
  { id: 1, productName: 'Future Sofa', stage: 'Rendering 3D mesh', progress: 72, eta: '12 min', status: 'processing' },
  { id: 2, productName: 'Solar Tote', stage: 'Style matching', progress: 100, eta: 'Ready', status: 'success' },
  { id: 3, productName: 'Aero Speaker', stage: 'Quality check', progress: 56, eta: '23 min', status: 'processing' },
];

export const currentUser: UserProfile = {
  id: 101,
  name: 'Aisha N.',
  email: 'aisha@douche.com',
  role: 'customer',
  membership: 'Platinum',
  location: 'Douala, Cameroon',
  preferences: ['Furniture', '3D Tech', 'Minimalist design'],
  avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
  bio: 'Exploring premium 3D shopping journeys with curated product recommendations.',
};

export const vendorUser: UserProfile = {
  id: 202,
  name: 'Samuel K.',
  email: 'samuel@kokora.com',
  role: 'vendor',
  membership: 'Verified Seller',
  location: 'Buea, Cameroon',
  preferences: ['Analytics', 'Inventory', 'AI generation'],
  avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
  bio: 'Vendor focused on premium African fashion and AI-powered model previews.',
};
